CREATE DATABASE IF NOT EXISTS dental_photo_doc;
USE dental_photo_doc;

CREATE TABLE IF NOT EXISTS documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  ficha VARCHAR(50) NOT NULL,
  doctor VARCHAR(255) NOT NULL,
  fecha VARCHAR(50) NOT NULL,
  fotos JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 